name: Lint Check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Verify formatting
        run: dotnet format --verify-no-changes --severity warn
